import Head from "next/head";
import styles from "../styles/Home.module.css";
import Dashboard from "../src/page-components/Dashboard";

export default function Home({ rides, user }) {
  // console.log(rides);
  return (
    <div className={styles.container}>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard rides={rides} user={user} />
    </div>
  );
}

export async function getServerSideProps() {
  let res = await fetch(`https://assessment.api.vweb.app/rides`);
  const data = await res.json();

  res = await fetch(`https://assessment.api.vweb.app/user`);
  const details = await res.json();
  return { props: { rides: data, user: details } };
}
