import { useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Dashboard from "../src/page-components/Dashboard";

export default function Home({ rides, user }) {
  // console.log(rides);
  return (
    <div className={styles.container}>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard rides={rides} user={user} />
    </div>
  );
}

export async function getServerSideProps() {
  let res = await fetch(`https://assessment.api.vweb.app/rides`);
  const data = await res.json();

  res = await fetch(`https://assessment.api.vweb.app/user`);
  const userDetails = await res.json();

  data.forEach((detail) => {
    detail.station_path.push(detail.destination_station_code);
    detail.station_path.unshift(detail.origin_station_code);
  });

  data.forEach((rides) => {
    let min = userDetails.station_code;
    rides.station_path.forEach((ride) => {
      min = Math.min(Math.abs(ride - userDetails.station_code), min);
    });
    rides["distance"] = min;
  });
  return { props: { rides: data, user: userDetails } };
}
