import Head from "next/head";
import styles from "../styles/Home.module.css";
import Dashboard from "../src/page-components/Dashboard";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  );
}
